_id: 78096000-3e9d-11eb-b8c3-6f037a3557d9
parentId: ''
message: 'Научите бесплатно трговање девизама на мрежи. https://rs.forex-is.com'
name: Forexlaunty
email: 52a41f30f987d131e932d8e36593831c
url: 'https://ee.forex-is.com'
date: '2020-12-15T06:19:21.347Z'
