_id: 0f65bc00-8660-11eb-b8c3-6f037a3557d9
parentId: ''
message: 'Daglige forex trading signaler. https://no.forex-trading-is.com'
name: Forextew
email: 7e26211d06149659fe1fe3a0470eb5b7
url: 'https://id.forex-trading-is.com'
date: '2021-03-16T14:01:10.455Z'
