_id: 86948750-8db5-11eb-b8c3-6f037a3557d9
parentId: ''
message: >-
  breaking news in nigeria
  https://www.fmohconnect.gov.ng/international_cooperation.html
name: AngelSpale
email: ea3a02060c4cf710e587e0f88fe5ba9d
url: 'https://fmohconnect.gov.ng/'
date: '2021-03-25T22:00:35.610Z'
